title = "JIN Hui"
baseURL = "https://jinhui.de"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "solarized-dark"
enableGitInfo = false
publishdir = "docs"

[params]
address = "Stuttgart, DE"
email = "hijcss@gmail.com"
favicon = "/favicon.ico"
firstName = "JIN"
lastName = "Hui"
phone = "dont call"
profileImage = "img/ProfilePic.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/hui-jin-a502b4183/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/char-iot/"
name = "GitHub"

[[params.handles]]
link = "https://gitlab.com/char-iot/"
name = "GitLab"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"