title = "JIN Hui"
baseURL = "https://jinhui.de"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "solarized-dark"
enableGitInfo = false
publishdir = "docs"

[params]
address = "Stuttgart, DE"
email = "hijcss@gmail.com"
favicon = "/favicon.ico"
firstName = "Hui"
lastName = "JIN"
phone = "+49-711-1234567"
profileImage = "img/ProfilePic.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true
description = "description here"

[params.google]

[params.google.analytics]
trackerID = "UA-158231626-1"

[[params.handles]]
link = "https://www.linkedin.com/in/hui-jin-a502b4183/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/char-iot/"
name = "GitHub"

[[params.handles]]
link = "https://gitlab.com/char-iot/"
name = "GitLab"


## Social Accounts
[params.social]
    github = "char-iot"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    telegram = "@char_iot"
    email = "hijcss@gmail.com"
    # gravatar = "hijcss@gmail.com"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"